config/routes.rb
Rails.application.routes.draw do
  get 'heats/create'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'meetings#index'
  
  resources :meetings
  resources :heats

end

app/models/meeting.rb
class Meeting < ApplicationRecord
    has_many :heats, dependent: :destroy
    validates :date, :home_team, :away_team, presence: true
    

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
    before_action :set_meeting, only: [:show, :edit, :update, :destroy]
    
    def index
        @meetings = Meeting.all.order(date: :desc)
    end
    
    def edit
    end
    
    def new
        @meeting = Meeting.new
    end
    
    def create
        @meeting = Meeting.create(meeting_params)
        respond_to do |format|
            if @meeting.save
                format.html { redirect_to meetings_path, notice: 'Meeting was successfully created.' }
            else
                format.html { render :new, notice: 'Oops!' }
            end
        end
    end

    
    def show
        @meeting = Meeting.find(params[:id])
    end
    
    
    def update
        respond_to do |format|
          if @meeting.update(meeting_params)
            format.html { redirect_to  meetings_path, notice: 'Meeting was successfully updated.' }
          else
            format.html { render :edit, notice: 'Oops!' }
          end
        end
    end
    
    def destroy
        @meeting.destroy
        respond_to do |format|
          format.html { redirect_to meetings_url, notice: 'Meeting was deleted.' }
        end
    end
    
    private
    def set_meeting
      @meeting = Meeting.find(params[:id])
      
    end
    
    def meeting_params
        params.require(:meeting).permit(:date, :home_team, :away_team, :home_score, :away_score, 
        :home_rider_1, :home_rider_2, :home_rider_3,  :home_rider_4, :home_rider_5, :home_rider_6, :home_rider_7,
        :away_rider_1, :away_rider_2, :away_rider_3, :away_rider_4, :away_rider_5, :away_rider_6, :away_rider_7)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
    
    def fastest_heat(id)
       result = Heat.where(meeting_id:id).minimum("heat_time")
    end
    
    def gate_results(id, gate_number)
        gate_score = 0
        gate_blue = 0
        gate_red = 0
        gate_white = 0
        gate_yellow = 0
        heats = Heat.where(meeting_id:id)
        
        heats.each do |heat|
            blue = Blue.where(gate_number: gate_number, heat_id: heat.id).sum(:score)
            gate_blue += blue
            red = Red.where(gate_number: gate_number, heat_id: heat.id).sum(:score)
            gate_red += red
            white = White.where(gate_number: gate_number, heat_id: heat.id).sum(:score)
            gate_white += white
            yellow = Yellow.where(gate_number: gate_number, heat_id: heat.id).sum(:score)
            gate_yellow += yellow
        end
        
        gate_score = gate_blue.to_i + gate_red.to_i + gate_white.to_i + gate_yellow.to_i
    end
    
    
    
    def meeting_home_score(id)
        heats = Heat.where(meeting_id:id)
        blue_result = 0
        red_result = 0
        heats.each do |heat|
            heat.blues.each do |blue|
                blue_result += blue.score
            end
            heat.reds.each do |red|
                red_result += red.score
            end
        end
        home_score = blue_result + red_result
    end
    
    def meeting_away_score(id)
        heats = Heat.where(meeting_id:id)
        white_result = 0
        yellow_result = 0
        heats.each do |heat|
            heat.whites.each do |white|
                white_result += white.score
            end
            heat.yellows.each do |yellow|
                yellow_result += yellow.score
            end
        end
        away_score = white_result + yellow_result
    end
    
    def home_rider_score(id, rider)
        meeting = Meeting.find(id)
        heats = Heat.where(meeting_id: id)
        total = 0
        blue_score = 0
        red_score = 0
        heats.each do |heat|
            blue = Blue.where(rider_name: rider, heat_id: heat.id).sum(:score)
            blue_score += blue
            red = Red.where(rider_name: rider, heat_id: heat.id).sum(:score)
            red_score += red
        end
        total = blue_score.to_i + red_score.to_i
    end
    
    def away_rider_score(id, rider)
        meeting = Meeting.find(id)
        heats = Heat.where(meeting_id: id)
        total = 0
        white_score = 0
        yellow_score = 0
        heats.each do |heat|
            white = White.where(rider_name: rider, heat_id: heat.id).sum(:score)
            white_score += white
            yellow = Yellow.where(rider_name: rider, heat_id: heat.id).sum(:score)
            yellow_score += yellow
        end
        total = white_score.to_i + yellow_score.to_i
    end
    
end

app/views/meetings/_form.html.erb
<%= bootstrap_form_for(@meeting) do |f| %>
    <%= f.date_select :date, format: 'dd-MM-yyyy', layout: :default %>
    <%= f.select :home_team, [["Belle Vue Aces"], 
                                ["King's Lynn Stars"],
                                ["Leicester Lions"],
                                ["Poole Pirates"],
                                ["Rye House Rockets "],
                                ["Somerset Rebels "],
                                ["Swindon Robins"],
                                ["Wolverhampton Wolves"]],
    prepend: "Home team", skip_label: true, layout: :inline %>
    
    
    
    <%= f.text_field :home_rider_1, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :home_rider_2, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :home_rider_3, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :home_rider_4, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :home_rider_5, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :home_rider_6, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :home_rider_7, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    
    <%= f.select :away_team, [["Belle Vue Aces"], 
                                ["King's Lynn Stars"],
                                ["Leicester Lions"],
                                ["Poole Pirates"],
                                ["Rye House Rockets "],
                                ["Somerset Rebels "],
                                ["Swindon Robins"],
                                ["Wolverhampton Wolves"]],
    prepend: "Away team", skip_label: true, layout: :inline %>
    
    <%= f.text_field :away_rider_1, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :away_rider_2, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :away_rider_3, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :away_rider_4, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :away_rider_5, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :away_rider_6, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.text_field :away_rider_7, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-3"%>
    <%= f.submit "Save" %>
<% end %>

app/views/meetings/edit.html.erb
<h3>Edit meeting</h3>

<%= render 'form', meeting: @meeting %>

app/views/meetings/index.html.erb
<h3>Meetings</h3>


<table class="table table-hover table-sm">
  <thead class="thead-light">
    <tr>
        <th scope="col">Date</th>
        <th scope="col">Home</th>
        <th scope="col">Away</th>
        <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @meetings.each do |meeting| %>
      <tr>
          <td><%= meeting.date.strftime("%d %b %y") %></td>
          <td><%= meeting.home_team %>: <%= meeting_home_score(meeting.id) %></td>
          <td><%= meeting.away_team %>: <%= meeting_away_score(meeting.id) %></td>
          <td><%= link_to 'Show', meeting %></td>
          <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
          <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>







<%= link_to 'New meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h3>New meeting</h3>

<%= render 'form', heat: @heat %>

app/views/meetings/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col"><h5><%= @meeting.date.strftime("%A %B %C") %></h5></div>
    </div>
    <div class="row">
        <div class="col"><h6><%= @meeting.home_team %>: <%= meeting_home_score(@meeting.id) %></h6></div>
        <div class="col"><h6><%= @meeting.away_team %>: <%= meeting_away_score(@meeting.id) %></h6></div>
        <div class="col"><%= button_to "Add heat", new_heat_path, params: {:meeting_id => @meeting.id}, method: :get %></div>
    </div>
    

    <p></p>
    
    <table class="table table-striped table-bordered">
        <tbody>
            <% @meeting.heats.each do |heat| %>
            <tr>
                <td>Heat <%= heat.heat_number %> : <%= heat.heat_time %></td>
                <td><%= button_to 'Edit', edit_heat_path(heat.id), method: :get, class: 'btn btn-sm' %></td>
                <td><%= button_to 'Delete', heat_path(heat.id), method: :delete, class: 'btn btn-sm', data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <tr>
                <% heat.reds.each do |red| %>
                <td style="background-color:#ffcccc"><%= red.rider_name %> : <%= red.score %></td>
                <% end %>
                <% heat.blues.each do |blue| %>
                <td style="background-color:#cce6ff"><%= blue.rider_name %> : <%= blue.score %></td>
                <% end %>
                <% heat.whites.each do |white| %>
                <td><%= white.rider_name %> : <%= white.score %></td>
                <% end %>
                <% heat.yellows.each do |yellow| %>
                <td style="background-color:#ffffcc"><%= yellow.rider_name %> : <%= yellow.score %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
    
    <p></p>
    <h6>Fastest heat: <%= fastest_heat(@meeting.id) %></h6>
    <p></p>
    <h6>Rider results</h6>
    <table class="table table-hover table-sm">
        <thead class="thead-light">
            <tr>
                <th>#</th>
                <th><%= @meeting.home_team %></td>
                <th>Total</td>
                <th><%= @meeting.away_team %></td>
                <th>Total</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td><%= @meeting.home_rider_1 %></td>
                <td><%= home_rider_score(@meeting.id, @meeting.home_rider_1) %></td>
                <td><%= @meeting.away_rider_1 %></td>
                <td><%= away_rider_score(@meeting.id, @meeting.away_rider_1) %></td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td><%= @meeting.home_rider_2 %></td>
                <td><%= home_rider_score(@meeting.id, @meeting.home_rider_2) %></td>
                <td><%= @meeting.away_rider_2 %></td>
                <td><%= away_rider_score(@meeting.id, @meeting.away_rider_2) %></td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td><%= @meeting.home_rider_3 %></td>
                <td><%= home_rider_score(@meeting.id, @meeting.home_rider_3) %></td>
                <td><%= @meeting.away_rider_3 %></td>
                <td><%= away_rider_score(@meeting.id, @meeting.away_rider_3) %></td>
            </tr>
            <tr>
                <th scope="row">4</th>
                <td><%= @meeting.home_rider_4 %></td>
                <td><%= home_rider_score(@meeting.id, @meeting.home_rider_4) %></td>
                <td><%= @meeting.away_rider_4 %></td>
                <td><%= away_rider_score(@meeting.id, @meeting.away_rider_4) %></td>
            </tr>
            <tr>
                <th scope="row">5</th>
                <td><%= @meeting.home_rider_5 %></td>
                <td><%= home_rider_score(@meeting.id, @meeting.home_rider_5) %></td>
                <td><%= @meeting.away_rider_5 %></td>
                <td><%= away_rider_score(@meeting.id, @meeting.away_rider_5) %></td>
            </tr>
            <tr>
                <th scope="row">6</th>
                <td><%= @meeting.home_rider_6 %></td>
                <td><%= home_rider_score(@meeting.id, @meeting.home_rider_6) %></td>
                <td><%= @meeting.away_rider_6 %></td>
                <td><%= away_rider_score(@meeting.id, @meeting.away_rider_6) %></td>
            </tr>
            <tr>
                <th scope="row">7</th>
                <td><%= @meeting.home_rider_7 %></td>
                <td><%= home_rider_score(@meeting.id, @meeting.home_rider_7) %></td>
                <td><%= @meeting.away_rider_7 %></td>
                <td><%= away_rider_score(@meeting.id, @meeting.away_rider_7) %></td>
            </tr>
        </tbody>
    </table>
    <p></p>
    <h6>Gate results</h6>
    <table class="table table-hover table-sm">
        <thead class="thead-light">
            <tr>
                <th>Gate</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td><%= gate_results(@meeting.id, 1) %></td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td><%= gate_results(@meeting.id, 2) %></td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td><%= gate_results(@meeting.id, 3) %></td>
            </tr>
            <tr>
                <th scope="row">4</th>
                <td><%= gate_results(@meeting.id, 4) %></td>
            </tr>
        </tbody>
    </table>
</div>